#!/bin/sh

case "$1" in
    start)
        echo "Loading tsc_freq_khz module..."
        modprobe tsc_freq_khz
        ;;
    stop)
        echo "Unloading tsc_freq_khz module..."
        rmmod tsc_freq_khz
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0